services:

    kopia:
        image: kopia/kopia:latest
        container_name: kopia 
        user: "1000:1000"   
        privileged: true                    
        restart: unless-stopped
        ports:
            - "51515:51515"
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        devices:
            - /dev/fuse:/dev/fuse:rwm            
        command:
            - server
            - start
            - --disable-csrf-token-checks
            - --insecure            
            - --address=0.0.0.0:51515
            - --server-username=User
            - --server-password=p4ssw0rd
        environment:
            USER: "User"            
            KOPIA_PASSWORD: "p4ssword"
            TZ: Europe/Madrid            
        volumes:
            - /root/docker:/source     
            - ./kopia/config:/app/config
            - ./kopia/cache:/app/cache
            - ./kopia/logs:/app/logs
            - ./kopia/data:/data:ro     
